version: '3.7'
services:
  superset:
    container_name: superset
    restart: always
    build: ./superset
    image: superset_server
    volumes:
     - ./superset/superset-conf/config:/etc/superset
     - ./superset/superset-conf/data:/var/lib/superset
     - superset:/app/superset_home
    ports:
     - "8088:8088"
    environment:
     - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
volumes:
  psql_data:
  superset:
